/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ii.proyecto;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author bcamp
 */
public class Comodin extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Comodin
     */
    Random rand = new Random();
    int rand1 = rand.nextInt(9-1)+1;
    int rand2 = rand.nextInt(9-1)+1;
    int rand3 = rand.nextInt(9-1)+1;
    Thread h1;
    String activado = "si";
    int i = 60;
    
    public Comodin() {
        initComponents();
        h1 = new Thread(this);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    

    @Override
    public void run() {

        Thread time = Thread.currentThread();
        while (time == h1) {
            i = i - 1;
            if(i<=9){
                txtTime.setText("0:0" + i);
            }else{
            txtTime.setText("0:" + i);
            }
            if (i == 15) {
                txtTime.setBackground(Color.orange);
            }
            if (i == 5) {
                txtTime.setBackground(Color.red);
            }
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "Tiempo agotado, comodin perdido");
                dispose();
                h1.suspend();
            }
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
    
    public void desbloqueo(int rand1, int rand2, int rand3) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        btnAbrir = new javax.swing.JButton();
        sprNum1 = new javax.swing.JSpinner();
        sprNum2 = new javax.swing.JSpinner();
        sprNum3 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        jLabel1.setText("Tiempo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        txtTime.setEditable(false);
        txtTime.setText("1:00");
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, -1));

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, -1));

        sprNum1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        getContentPane().add(sprNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 30));

        sprNum2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        getContentPane().add(sprNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 40, 30));

        sprNum3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        getContentPane().add(sprNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
       if("si".equals(activado)){                           
        run();
        h1.start();
        System.out.println(rand1+"  "+rand2+"  "+rand3);
       }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if(rand1==(int) sprNum1.getValue() && rand2==(int) sprNum2.getValue() && rand3==(int) sprNum3.getValue()){
            JOptionPane.showMessageDialog(null, "Logrado, Juego terminado");
            h1.suspend(); 
            dispose();
            Laberinto ven = new Laberinto();
            ven.setVisible(true);
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comodin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comodin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comodin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comodin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Comodin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner sprNum1;
    private javax.swing.JSpinner sprNum2;
    private javax.swing.JSpinner sprNum3;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

}
